### ISSUE TITLE
сделать новый TsarPlugin

### ISSUE THREAD

**Issue by zoocide** [zoocide/tsar-test-template#4]
- [x] Команда `init`.
- [x] Команда `check` (по-умолчанию).
- [x] Команда `clean`.
- [x] Команда `show`.
- [x] Переносить переменные из `env::` в окружение команды `run`.

задачи плагина:

1. `cp -r $copy` в директорию res
2. `cd res`
3. `system($run)`
4. diff/init
a. `diff $_, ../$sample_dir/$_ for @sample;`
b. `diff $_, ../$sample_dir/$sample_map{$_} for keys %sample_map;`

**Comment by kaniandr** [comment]
Переменные определяемые плагином:
- `exe_extension` - расширение используемое в имени исполняемых фалов на текущей платформе `$platform` (например `.exe` для ОС Windows);
- `run_prefix` - префикс предшествующий имени запускаемого исполняемого файла в зависимости от платформы (`./` - для OC Linux, пустой префикс для ОС Windows);
- `env::` - группа переменных, устанавливающая значения переменных окружения перед запуском теста, например `env::DVMH_NUM_CUDAS=1` установит значение переменной окружения `DVMH_NUM_CUDAS` для запуска DVMH программы, соответствующей данному тесту, на графическом ускорителе.
