### ISSUE TITLE
привести тесты к новому виду

### ISSUE THREAD

**Issue by zoocide** [zoocide/tsar-test-template#6]
- [x] преобразовать тесты analysis/canonical_loop
- [x] преобразовать тесты analysis/da_di
- [x] убрать из тестов для анализа комментарии CHECK
- [x] преобразовать тесты transform/de_decls
- [x] преобразовать тесты transform/dvmh_sm
- [x] преобразовать тесты transform/inline
- [x] преобразовать тесты transform/openmp
- [x] преобразовать тесты transform/propagate
- [x] преобразовать тесты transform/replace
- [x] преобразовать тесты transform/replace_const

- переместить тесты в отдельные директории
- разделить префиксы на отдельные задачи ~(`-check-prefix` идет в `sample=$name.$platform.c`)~
- разделить список `@run` на отдельные задачи
- поправить конфигфайлы для новой системы

**Comment by kaniandr** [comment]
- поправить тестовые наборы, в том числе добавить явно параллельные области (хочу убрать из CMake их неявную расстановку перед запуском теста)
