### ISSUE TITLE
поправить CMakeLists

### ISSUE THREAD

**Issue by zoocide** [zoocide/tsar-test-template#7]
Должны задаваться переменные перед запуском тестов:

- [x] `clang` - путь до используемой версии компилятора Clang;

- [x] `tsar` - путь до используемой версии инструмент TSAR;
- [x] `include` - список дополнительных путей до заголовочных файлов, которые будут использованы при запуске инструмента TSAR;
- [x] `dvm` - путь до скрипта `dvm`, отвечающего за компиляцию и запуск DVMH программ;
- [x] `platform` - тип платформы на которой выполняется запуск;

**Comment by kaniandr** [comment]
- [ ] добавить утилиту sapfor-test,
    - устанавливать переменные окружения для плагина внутри CMake,
    - добавить правила установки для sapfor_test,
    - сделать платформа-зависимые реализации утилиты

**Comment by kaniandr** [comment]
- [ ] добавить CMake правилf сборки для проектов Clean..., удаляющих результаты последнего запуска тестов

**Comment by kaniandr** [comment]
Т.к. был принято решение отделить репозиторий с тестами от репозитория TSAR, то необходимо добавить в CMakeLists поиск TSAR. При этом надо сохранить возможность собирать проект с тестами, как поддиректорию проекта TSAR, чтобы сохранить цели make (проекты в VS), отвечающие за запуск тестов.
