### ISSUE TITLE
подготовить документацию для использования системы третьими лицами

### ISSUE THREAD

**Issue by zoocide** [zoocide/tsar-test-template#8]
- [x] устройство системы
- [x] установка системы
- [x] структура теста
- [x] группы тестов
- [x] параллельность
- [x] инициализация тестов
- [x] запуск тестов
- [x] команда show
- [x] команда clean

**Comment by kaniandr** [comment]
Я добавил простое описание для show и clean. Но все-таки еще остается несколько вопросов:

- Должен ли быть `sapfor-test show dvmh_sm_6`, который покажет сравнение для всех запущенных под-тестов. Но тогда нужно отслеживать что запускалось или можно просто брать все, что есть в `res` и сравнивать с `show`. Но тогда будут потеряна расхождения вызванные тем, что какого-то файл нет в `res` или в `sample`.
- Должно ли отслеживаться какие под-тесты запускались, или хотя бы должна ли быть какая-то команда, которая это покажет. Т.к. перед запуском `compile` должен быть выполнен `tsar`, а если будет выполнен `seq`, то компиляция пройдет, но это будет последовательная программа, а не параллельная.
- Видимо должен быть `clean:all`, в динамическом анализаторе ведь что-то такое есть?

**Comment by zoocide** [comment]
`show dvm_sm_6` можно было бы заменить на `show dvm_sm_6/all`, поскольку сейчас указывать директорию в качестве задания нельзя.
Когда pts будет поддерживать указания в task-set файлах других task-set файлов (https://github.com/zoocide/pts/issues/11), можно будет группировать задачи и включать одни группы в другие. Например,
*dvmh_sm_6/dvm_compile:*
````bash
seq
  ./tsar
  ./compile
end_seq
````
*dvmh_sm_6/dvm_run_threads:*
````bash
./run: env::DVMH_NUM_THREADS=1, env::DVMH_NUM_CUDAS=0
./run: env::DVMH_NUM_THREADS=2, env::DVMH_NUM_CUDAS=0
./run: env::DVMH_NUM_THREADS=1, env::DVMH_NUM_CUDAS=0
./run: env::DVMH_NUM_THREADS=2, env::DVMH_NUM_CUDAS=0
````
*dvmh_sm_6/dvm_run_cudas:*
````bash
seq
  ./run: env::DVMH_NUM_THREADS=0, env::DVMH_NUM_CUDAS=1
  ./run: env::DVMH_NUM_THREADS=12, env::DVMH_NUM_CUDAS=1
end_seq
````
*dvmh_sm_6/all*
````bash
./dvm_compile
parallel
  ./dvm_run_threads
end_parallel
./dvm_run_cudas
````
*check:*
````bash
parallel
  dvmh_sm_4/dvm_compile
  dvmh_sm_5/dvm_compile
  dvmh_sm_6/dvm_compile
end_parallel
parallel
  dvmh_sm_4/dvm_run_threads
  dvmh_sm_5/dvm_run_threads
  dvmh_sm_6/dvm_run_threads
  ./dvm_run_cudas
  seq
    dvmh_sm_4/dvm_run_cudas
    dvmh_sm_5/dvm_run_cudas
    dvmh_sm_6/dvm_run_cudas
  end_seq
end_parallel
````

**Comment by kaniandr** [comment]
`clean` работает для конкретной задачи, или можно как-то почистить все тесты из набора?

**Comment by zoocide** [comment]
технически `clean` просто устанавливает переменную `action=clean` для всех последующих задач. Так что `pts clean task1 task2 ...` почистит все указанные задачи.

**Comment by kaniandr** [comment]
То есть кроме `check`, `init` есть еще и `clean`.
Может нужно иметь и соответствующий тестовый набор, чтобы просто писать `sapfor-test clean` :
```bash
dvmh_sm_6/tsar:action=clean
dvmh_sm_6/compile:action=clean
dvmh_sm_6/run:action=clean
dvmh_sm_6/seq:action=clean
...
```

**Comment by kaniandr** [comment]
> На счет compile и seq, было бы лучше, чтобы они работали в разных директориях, тогда бы не пришлось каждый раз все копировать и перекомпилировать. Нужна переменная с именем директории результатов, с некоторым значением по-умолчанию.

Какое лучше имя для переменной:
- [ ] result_dir
- [ ] work_dir
- [ ] run_dir
- [ ] свой вариант

**Comment by kaniandr** [comment]
А как работает clean:

- удаляет всю директорию с результатами, но тогда фактически не важно какое имя под-теста написать, если у них совпадают директории;
- удаляет только файлы относящиеся к под-тесту, но анализатор может создать какие-то дополнительные файлы, например *.orig-файлы создаются после преобразования, в них содержатся исходные версии программ, эти файлы нигде не упоминаются, но должны быть удалены.

**Comment by zoocide** [comment]
> Может нужно иметь и соответствующий тестовый набор, чтобы просто писать `sapfor-test clean` :

Я вижу в этом излишнее дублирование. Ведь каждый тест придется добавить в каждый список.
Для задач check и clean по сути списки одинаковые.
В dyna имеется список `all`, в который я добавляю задачи, а потом использую его так:
````bash
> pts init all  #< для инициализации всех тестов
> pts all       #< для проверки всех тестов
> pts clean all #< для очистки директорий с тестами
> pts init task #< для инициализации указанного теста
> pts show task #< для отображения результатов теста
> # и так далее
````
Если не нравится, что помимо `clean` нужно писать еще что-то, то можно создать файл clean:
````bash
clean
./all
````
и потом вызывать его `sapfor-test ./clean` (Здеть `./` указывает, что этот файл нужно искать в текущей директории, а не в path).

**Comment by zoocide** [comment]
> А как работает clean:
> 
> * удаляет всю директорию с результатами, но тогда фактически не важно какое имя под-теста написать, если у них совпадают директории;
> * удаляет только файлы относящиеся к под-тесту, но анализатор может создать какие-то дополнительные файлы, например *.orig-файлы создаются после преобразования, в них содержатся исходные версии программ, эти файлы нигде не упоминаются, но должны быть удалены.

Если удалять всю директорию, будут затронуты все задачи, работающие в этой директории. Это, наверное, нежелательное поведение.
Плагин может попытаться вывести имена файлов для удаления из той информации, что ему известна. Или же эти файлы должны быть явно заданы. Или и то и другое.
Кстати, никто не запрещает использовать разные плагины для тестов на анализ, преобразования, компиляцию, запуск и т.д. А сами плагины не обязательно копировать, есть наследование. Т.е., например, плагин может лишь определять функцию, соответствующую `action=clean`.

**Comment by kaniandr** [comment]
Но вроде бы сначала мы говорили о том, что плагин должен быть максимально простым, делать фиксированную последовательностью действий и не зависеть от команды `run`. А теперь получается, что должна быть какая-то смесь: с одной стороны команду можно задать любую, а с другой стороны, если плагины разные, то они ожидают от нее определенное поведение.

**Comment by zoocide** [comment]
Ограничения на плагины в принципе нет. Главное, чтобы они не ломали варианты использования.
Хочешь универсальный с подробным описанием действий в конфигурационных файлах, а хочешь специализированный, который выполняет строго оговоренные действия, но задавать нужно всего пару имен файлов. Например, для элементарных тестов подойдет плагин, который не принимает вообще никаких параметров, кроме `action`, все имена файлов будут зашиты в нем. Можно хоть под каждый тест заводить свой плагин. Хотя с другой стороны, количество текста в конфигурационном файле не имеет особого значения, т.к. скорее всего файл будет просто копироваться при создании нового теста.

Тут, что больше нравится. С точки зрения времени работы pts, наличие десятка дополнительных плагинов будет незаметно на общем фоне. Конечно проще задокументировать один плагин и не объяснять всем, когда какой использовать.

**Comment by zoocide** [comment]
Короче, для нашего универсального плагина подойдет переменная `clean_files`, которая будет содержать имена файлов для удаления во время `clean`.

**Comment by kaniandr** [comment]
А ведь есть еще такая особенность: сравниваться будет то, что указано в `sample`. Если файл не указан в `sample`, но присутствует в папке с результатами, то это ошибка. Но возможны два варианта:

- файл относится к файлам из `copy`. Тогда его можно было бы не проверять, но наверное надо убедиться, что он совпадает и сходным файлом из директории теста.
- файл не относится к файлам из `copy`, например, файлы `*.c.orig`. Тогда получается, эти файлы тоже должны быть в `sample`. И наверное это правильно, ведь они являются результатом работы анализатора. Но это может быть например исполняемый файл программы, который получился после компиляции, его не должно быть в `sample`, мы же не будем бинарные файлы сравнивать, но и в `copy` его нет.

Мне кажется, что нужно добавить переменную `ignore`, указывающую какие файлы игнорировать при сравнении. Тогда удалять нужно то, что в `ignore`, `copy`, `sample`, `sample_map`. При этом исполняемые файлы и `*.c.orig` можно указывать в `ignore`.

**Comment by kaniandr** [comment]
По поводу списка задач `all` у меня была такая мысль, но ведь задачи `init` и `check` имеют свои разные параметры внутри списка, кроме того одни и те же тесты могут запускаться многократно (внутри `check`) и для них есть вполне определенные правила параллельного/последовательного запуска.

Может быть стоит иметь просто список всех тестов в виде `all` на всякий случай. Только вопрос, если будет сделан `clean` и будут удаляться файлы в параллельном режиме, не приведет ли это к проблемам, если разные под-тесты захотят удалить один и тот же файл?

**Comment by kaniandr** [comment]
С `ignore` и `work_dir` будет так:

```bash
#tsar.conf
plugin = TsarPlugin
sources = main.c
copy = $sources include/main.h
ignore = main.c.orig
sample = $copy output.txt
options = -clang-struct-replacement
run = "$tsar $sources $options >output.txt 2>&1"
```

```bash
#compile.conf
plugin = TsarPlugin
sources = main.c
ignore = main$exe_extension
options = -o main$exe_extension
sample = compile.txt
run = "$dvm c $sources $options >compile.txt 2>&1"
```

```bash
#run.conf
plugin = TsarPlugin
output = run_nt${env::DVMH_NUM_THREADS}_nc${env::DVMH_NUM_CUDAS}_g${grid}.txt
sample_map = $output run.txt
run = "$dvm run main${exe_extension} $grid >'$output' 2>&1"
```

```bash
#seq.conf
plugin = TsarPlugin
sources = main.c
copy = $sources include/main.h
ignore = seq${exe_extension}
work_dir = seq_res
sample = run.txt
options = -O3 -o seq$exe_extension
run = "$clang $sources $options && ${run_prefix}seq${exe_extension} >run.txt 2>&1"
```

**Comment by zoocide** [comment]
Конечно лучше удалать последовательно. Но в данном случае ничего плохого не произойдет, только может предупреждение вылезет.

**Comment by zoocide** [comment]
> Если файл не указан в `sample`, но присутствует в папке с результатами, то это ошибка.

Не понимаю, почему это должно быть ошибкой. Как по мне, так пусть порождает, что хочет, может прога логи пишет в зависимости от переменных среды. Это уже относится к разряду побочных действий, которые данным тестированием покрыть не получится, ну или нужно сильно заморочиться, ведь создание файлов - самое безобидное, что может сделать программа.
Кроме того, каждая задача создает свои собственные файлы, о которых другие задачи понятия не имеют. Они же работают в одной директории.
Так что я бы предпочел `clean_files = $sample $copy and anything else`.

**Comment by kaniandr** [comment]
Проблема в том, что это может быть важный файл. Например, анализатор сделал преобразование, которое не должен был делать. Правда сейчас, так как мы отказались от -output-suffix, то если исходить из того, что анализатор только меняет файлы, а не создает новые, то проблем не будет. Но если, анализатор все-таки начнет создавать файлы дополнительно, то их отсутствие или наличие может быть ошибкой, которая должна ловится. 

К тому же, допустим, пусть порождает все, что хочет. Но, чтобы удалить эти файлы их все равно придется перечислить в `clean_files`, тогда чем это лучше, чем вариант с `ignore`. Просто у `clean_files` еще дополнительная функциональность появляется, эти файлы не проверяются при проверке теста.

**Comment by kaniandr** [comment]
Пришли к том, что не использовать `ignore`, т.к. разные конфигурационные файлы в этом случае должны указывать все возможные файлы из всех под-тестов. Используем переменную `clean`, указывая в ней все файлы, которые надо удалять, т.е. по умолчанию `sample` и `copy` не удаляются. Исходим из того, что даже если какой-то новый файл был создан как побочный эффект, то он будет где-то упомянут (в заголовках, в правилах компиляции) и его ошибочное создание будет таким образом обнаружено.
